const chai = require("chai");
const path = require("path");
const wasm_tester = require("circom_tester").wasm;
const assert = chai.assert;

//processes the witness generated by the circuit.
const getDecoratedOutput = async (circuit, witness) => {
    if (!circuit.symbols) await circuit.loadSymbols();
    const lines = {};

    for (let n in circuit.symbols) {
        if (witness[circuit.symbols[n].varIdx] === undefined) continue;
        let v = witness[circuit.symbols[n].varIdx].toString();
        lines[n] = v;
    }
    return lines
}

//test suite named "ReinforcedConcrete".
describe("ReinforcedConcrete", () => {

    let circuit;
    const katsInput = {
        // state: [
        //     "5318131563369638011325357465817405204783162951746317507525230104757675769920",
        //     "20614852220057270210230140702292305712326412047017090758177592319778719954884"
        // ]
        state: [
            "5318131563369638011325357465817405204783162951746317507525230104757675769920",
            "20614852220057270210230140702292305712326412047017090758177592319778719954884",
            "85782357235972357903750979027510925104827410792471029471927290471927529479204"
        ]
    };

    beforeEach(async () => {
        circuit = await wasm_tester(path.join(__dirname, "reinforcedConcreteTest.circom"));
    })

    //test case named "Compiles": checks if the circuit can compile and produce a valid witness
    it("Compiles", async () => {
        const w = await circuit.calculateWitness(katsInput);
        await circuit.checkConstraints(w);
    });

    //test case named "kats": verifies the correctness of the circuit's output against a known answer test
    it("kats", async () => {
        const w = await circuit.calculateWitness(katsInput);
        await circuit.checkConstraints(w);
        const output = await getDecoratedOutput(circuit, w);
        const result = output["main.hash"];
        console.log(result)
        assert(result, "20486399595719878967951200919723421339003691044935512594686796654746622621504");
    })
});